### ISSUE TITLE
FileExistsError: [Errno 17] File exists: '/run/user/1000/combo_locks'

### ISSUE THREAD

**Issue by goldyfruit** [forslund/combo-lock#14]
I got this error from the audio service (in OVOS), I'm not really sure why and how to fix it.
```
==> logs/audio.log <==
2022-10-02 21:39:17.551 - OVOS - ovos_utils.configuration:<module>:52 - WARNING - configuration moved to the `ovos_config` package. This submodule will be removed in ovos_utils 0.1.0

[Errno 17] File exists: '/run/user/1000/combo_locks'
Traceback (most recent call last):
  File "/home/snow/ovos/lib/python3.9/site-packages/combo_lock/combo_lock.py", line 100, in __init__
    path = join(get_ram_directory("combo_locks"), filename)
  File "/home/snow/ovos/lib/python3.9/site-packages/combo_lock/util.py", line 9, in get_ram_directory
    os.makedirs(path)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/run/user/1000/combo_locks'
```

Please find the `pip freeze` output.

```
adapt-parser==0.6.2
certifi==2022.9.24
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
combo-lock==0.2.3
dbus-next==0.2.3
fann2==1.0.7
filelock==3.8.0
gTTS==2.2.4
idna==3.4
json-database==0.7.0
kthread==0.2.3
langcodes==3.3.0
memory-tempfile==2.2.3
mycroft-messagebus-client==0.9.6
numpy==1.23.3
ovos-audio-plugin-simple==0.0.1
ovos-config==0.0.4
ovos-lingua-franca==0.4.5
ovos-PHAL==0.0.2
ovos-plugin-common-play==0.0.2
ovos-plugin-manager==0.0.19a4
ovos-skill-installer==0.0.5
ovos-stt-plugin-selene==0.0.1
ovos-stt-plugin-server==0.0.2
ovos-stt-plugin-vosk==0.1.4a1
ovos-tts-plugin-google-tx==0.0.3
ovos-tts-plugin-mimic==0.2.6
ovos-tts-plugin-mimic2==0.1.5
ovos-utils==0.0.25a6
ovos-workshop==0.0.8a1
ovos-ww-plugin-pocketsphinx==0.1.3
ovos-ww-plugin-precise==0.1.0
ovos-ww-plugin-precise-lite==0.1.2a2
padacioso==0.1.2
padaos==0.1.10
padatious==0.4.8
petact==0.1.2
pexpect==4.8.0
phoneme-guesser==0.1.1
pocketsphinx==0.1.15
precise-lite-runner==0.4.0
precise-runner==0.3.1
psutil==5.6.7
ptyprocess==0.7.0
PyAudio==0.2.12
pycparser==2.21
pyee==8.1.0
python-dateutil==2.8.2
pyxdg==0.28
PyYAML==5.4.1
quebra-frases==0.3.7
rapidfuzz==2.11.0
requests==2.28.1
scipy==1.9.1
selene-api==0.0.3
simplematch==1.3
six==1.16.0
sonopy==0.1.2
SpeechRecognition==3.8.1
srt==3.5.2
tflite-runtime==2.10.0
tornado==6.2
tqdm==4.64.1
urllib3==1.26.12
vosk==0.3.44
watchdog==2.1.9
websocket-client==1.4.1
websockets==10.3
xxhash==3.0.0
```

**Comment by forslund** [comment]
Thanks for reporting. Should be fixed by #13, closing. Feel free to reopen if the issue returns somehow.
